public enum MessageType{
    LOGIN,
    EDIT_EMPLOYEE,
    GET_EMPLOYEE,
    GET_EMPLOYEES_BY_HQ,
    GET_EMPLOYEES_BY_JOB,
    ADD_EMPLOYEE,
    DELETE_EMPLOYEE,
    GET_HEADQUARTER,
    ADD_HEADQUARTER,
    EDIT_HEADQUARTER,
    DELETE_HEADQUARTER
}
